### ISSUE TITLE
在jstorm中抛出这个错误java.lang.NoClassDefFoundError: org/apache/storm/shade/com/google/common/collect/ImmutableMap

### ISSUE THREAD

**Issue by darouwan** [chenatu/jstorm-kafka#1]
16760 [Spout_JSCTGW_144:10-SingleThreadSpoutExecutors] ERROR com.alibaba.jstorm.task.execute.spout.SpoutExecutors - spout execute error
java.lang.NoClassDefFoundError: org/apache/storm/shade/com/google/common/collect/ImmutableMap
        at storm.kafka.PartitionManager.commit(PartitionManager.java:256) ~[storm-dpi-0.0.1.jar:na]
        at storm.kafka.KafkaSpout.commit(KafkaSpout.java:191) ~[storm-dpi-0.0.1.jar:na]
        at storm.kafka.KafkaSpout.nextTuple(KafkaSpout.java:156) ~[storm-dpi-0.0.1.jar:na]
        at com.alibaba.jstorm.task.execute.spout.SpoutExecutors.nextTuple(SpoutExecutors.java:175) ~[jstorm-core-2.1.1.jar:na]
        at com.alibaba.jstorm.task.execute.spout.SingleThreadSpoutExecutors.run(SingleThreadSpoutExecutors.java:76) [jstorm-core-2.1.1.jar:na]
        at com.alibaba.jstorm.callback.AsyncLoopRunnable.run(AsyncLoopRunnable.java:95) [jstorm-core-2.1.1.jar:na]
        at java.lang.Thread.run(Thread.java:722) [na:1.7.0_07]
Caused by: java.lang.ClassNotFoundException: org.apache.storm.shade.com.google.common.collect.ImmutableMap
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_07]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_07]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_07]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_07]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423) ~[na:1.7.0_07]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[na:1.7.0_07]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356) ~[na:1.7.0_07]
        ... 7 common frames omitted

**Comment by darouwan** [comment]
已通过这个解决
http://snacktrace.com/artifacts/org.apache.storm/storm-rename-hack/1.0.1/org.apache.storm.hack.shade.com.google.common.collect.ImmutableMap
